#!/usr/bin/env python3
"""Generate sdk/om_cipher_layer6_data.js from the canonical JSON assets
in data/om_cipher/.

Single source of truth: the JSON files. The JS sidecar embeds the same
data so the browser bundle does not need to fetch JSON at runtime.

Run: python3 scripts/build_layer6_js.py
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(path):
    with open(os.path.join(ROOT, path), encoding="utf-8") as f:
        return json.load(f)


def main():
    mantras = load("data/om_cipher/mantra_table.json")
    stories = load("data/om_cipher/archetypal_stories.json")
    contemp = load("data/om_cipher/contemplations.json")

    out_path = os.path.join(ROOT, "sdk", "om_cipher_layer6_data.js")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(
            "// AUTOGENERATED — do not edit by hand.\n"
            "// Source: data/om_cipher/*.json\n"
            "// Regenerate via: python3 scripts/build_layer6_js.py\n"
            "\"use strict\";\n\n"
        )
        f.write("const MANTRA_TABLE = " + json.dumps(mantras, ensure_ascii=False) + ";\n\n")
        f.write("const ARCHETYPAL_STORIES = " + json.dumps(stories, ensure_ascii=False) + ";\n\n")
        f.write("const CONTEMPLATIONS = " + json.dumps(contemp, ensure_ascii=False) + ";\n\n")
        f.write(
            "const _exports = { MANTRA_TABLE, ARCHETYPAL_STORIES, CONTEMPLATIONS };\n"
            "if (typeof module !== \"undefined\" && module.exports) module.exports = _exports;\n"
            "if (typeof window !== \"undefined\") window.cuOmCipherLayer6 = _exports;\n"
        )
    print("wrote", out_path)


if __name__ == "__main__":
    main()
